# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/power-prophet',
                'doc_host': 'https://markkvdb.github.io',
                'git_url': 'https://github.com/markkvdb/power-prophet',
                'lib_path': 'power_prophet'},
  'syms': {'power_prophet.core': {'power_prophet.core.foo': ('core.html#foo', 'power_prophet/core.py')}}}
